### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by chaibenl** [USDA-ARS-GBRU/itsxpress#14]
Does ITSxpress trim paired-end reads that can't be merged because of lack of overlap?

**Comment by arivers** [comment]
No, it does not trim or return reads that it cannot merge.

**Comment by chaibenl** [comment]
What if I concatenate R1 and R2 and treat it as if it contains single end reads?

**Comment by arivers** [comment]
Could you provide more background about your sequences, sequencing type and what you plan do with the reads after trimming?  

I'd like to provide advice that makes sense for your scientific question.

**Comment by chaibenl** [comment]
Thank for the help!
I have 2X150 Illumina Miseq sets of Fungal ITS1. I found most of the reads can't be merged due to lack of overlap. I plan to run through dada2 or deblur and then classify the reads after rRNA trimming. The goal is to generate a feature table of Fungal taxonomic composition for the sampling environments. Hope that helps! Thank you.

**Comment by arivers** [comment]
The current version of ITSxpress uses pretty stringent BBmerge merging. You may want to do a test of the merging rate using  Pear with defaults, BBmerge with defaults and BBmerge using the parameter `maxmismatches=100`.  if your merging rate improves with those can change a setting on ITSxpress to get more merging.  

Ultimately the reads need to merge to use Dada2 because Dada2 uses the overlap to estimate the error rate.  Dada2 has a single-ended option but feeding merged reads into it violates the assumptions of the error model so you shouldn't do that.

**Comment by chaibenl** [comment]
Thank you for the explanation! I appreciate it!
