### ISSUE TITLE
ITSexpress and DADA2 with novaseq

### ISSUE THREAD

**Issue by science-chump** [USDA-ARS-GBRU/itsxpress#23]
Hello, I am trying to incorporate ITSexpress with my Novaseq data. I filtered my sequences using dada2 and then ran it through ITSexpress. I want to learn my error rates but I was wondering if ITSexpress will interfere with this process.

**Comment by arivers** [comment]
I don't think it should interfere.  Dada2 learns the error rates by position. In the overlapping ITS region those should be the same.  The ASVs will be shorter than if you did not trim the conserved regions so for long reads going into those regions you will have positional error rates in places where you did not have them before.  That may make the cumulative error rate different since the ASVs have different sequences.
