### ISSUE TITLE
Plugin error from itsxpress with AVITI data (FASTQ quality value (45) above qmax (41)

### ISSUE THREAD

**Issue by IrshadUlHaq1** [USDA-ARS-GBRU/itsxpress#51]
Hi,

I have been trying to analyze my sequencing data that come from an AVITI platform instead of Illumina. The FASTQ quality score are higher than 41, which results in an error when I run the itsxpress through qiime2-amplicon-2024.5. I have opened an issue on the qiime forum but out of curiosity I am asking here if you can help me get rid of this issue.

ERROR:root:Could not perform read merging with vsearch. Error from vsearch was:
vsearch v2.22.1_linux_x86_64, 503.3GB RAM, 128 cores

Merging reads

Fatal error: FASTQ quality value (45) above qmax (41)
By default, quality values range from 0 to 41.
To allow higher quality values, please use the option --fastq_qmax 45

**Comment by arivers** [comment]
Using BBTools reformat on your input data is probably the quickest option:

```
reformat.sh in=./pacbio/pacbio_samp1.fastq.gz out=pacbio_samp1_reformat.fastq.gz mincalledquality=2 maxcalledquality=41 qin=33
```
that would have no impact on the final results. ITSxpress only uses the Qual scores temporarily in the merging step and the difference between a 40 (1:10,000 error rate) and a 50 (1:100,000 error rate) is irrelevant because it is only used when there is a base pair mismatch in the alignment of the reads, but when you have a base with a .0001 error rate * a base with a 0.00001 error rate interacting, the chance of them not matching is tiny. Plus all the other overlapping sites are used for the alignment too. Then finally, the original higher read scores are returned at the end of the analysis.

That said, it is annoying to have to reformat your reads, so I'll test changing an internal setting to allow for higher Qual scores, so this error does not occur for future "high scoring" users.

As a side note, I don't think you need to use cutadapt before ITSxpress since the ITS cut sites are internal to the primer sites, but I've never tested the difference.

I'm labeling this as an enhancement to add support for Qual scores over 41.

**Comment by arivers** [comment]
I added support for quality scores over 41 in version 2.1.1.
