### ISSUE TITLE
PacBio ITS Extraction Issue

### ISSUE THREAD

**Issue by Chenshize0104** [USDA-ARS-GBRU/itsxpress#52]
Hi Professor,

We are currently working with a batch of sequencing data that comes from a PacBio platform instead of Illumina. For one of the primer pairs, we only obtained a partial ITS1 sequence (part ITS1 + 5.8S + ITS2 + LSU). In this case, when using the --region All command, we are unable to get the full partial ITS (part ITS1 + 5.8S + ITS2); instead, we only get part of ITS1 and ITS2. However, I would like to obtain the full partial ITS (part ITS1 + 5.8S + ITS2) because it provides more information than just part ITS1 or ITS2 alone.

Is there a way, similar to ITSx, to extract part ITS1, 5.8S, ITS2, and LSU so that I can freely combine them to get the full partial ITS (part ITS1 + 5.8S + ITS2)?

Thank you!
[test.zip](https://github.com/user-attachments/files/17044396/test.zip)

**Comment by arivers** [comment]
ITSxpress only trims the full ITS1, ITS2, orITS1-5.8s-ITS2 region The reason is that for ASVs any change in start or stop position creates a new ASV.  Allowing a variable start or stop would inflate your diversity metrics.  Was one of your primers designed to be in the middle of ITS 1 or were the reads not long enough?  ITSx is a more general tool so it may solve your need.

**Comment by arivers** [comment]
Please take a look at Closed Issue #50  for an idea of how to use some ITSxpress classes to write a script to do what you are asking.
