### ISSUE TITLE
PacBio CCS interleave error

### ISSUE THREAD

**Issue by Robvh-git** [USDA-ARS-GBRU/itsxpress#56]
Hello,

I'm trying to extract the ITS region from PacBio CCS reads using itsxpress by running following command:
`itsxpress --fastq ITS__1.fq.gz --single_end --log logfile.txt --outfile ITS_select_ITS__1.fastq --region ALL --threads 23`

this gives me the follow error message:

```
2024-10-24 13:53:35,899: INFO     Verifying the input sequences.
2024-10-24 13:53:35,978: ERROR    'File may be interleaved. ITSxpress will run with errors. Check BBmap reformat.sh to split interleaved files before using ITSxpress.
2024-10-24 13:53:35,978: ERROR    There appears to be an issue reading the input file ITS__1.fq.gz.
2024-10-24 13:53:35,978: ERROR    ITSxpress terminated with errors. See the log file for details.
2024-10-24 13:53:35,978: ERROR   
```
(the log file doesn't give additional info)

As this is PacBios CCS data, this data is not interleaved, and I'm unsure why `itsxpress` thinks it is. If - just to test - I use reformat.sh to 'de-interleave' this data, the interleaved files give the same error, so it is something about the format. 

In QIIME2, I get the same error.

Do you have any idea how to fix this issue? I see people using ITSxpress on PacBio data, so it should be possible.

I've attached the file.

[ITS__1.fq.gz](https://github.com/user-attachments/files/17506292/ITS__1.fq.gz)

**Comment by arivers** [comment]
Sorry, I just saw this request.  I was able to reproduce the error.   I'll look into what might be causing it.

**Comment by arivers** [comment]
This issue is caused by the way the function `_check_fastqs` uses sequence headers to determine if a file is interleaved [here](https://github.com/USDA-ARS-GBRU/itsxpress/blob/2dcdaab585d1192e1847e186cde7b7c2f05d1e09/itsxpress/main.py#L289). I disabled it and trimming worked. I will fix the validation logic and push an update. There are so many different ways to process PacBio data, this is a Pacbio header format I have not seen before.
