### ISSUE TITLE
BBMerge fails to merge reads

### ISSUE THREAD

**Issue by pilpel-lab** [USDA-ARS-GBRU/itsxpress#9]
Hey,
I'm trimming each of my samples separately because of the issue with the empty sequences.
By doing so, I could see the output of BBMerge, which turns out to perform badly compared to PEAR:

```
Pairs:                  26220
Joined:                 11798           44.996%
Ambiguous:              11712           44.668%
No Solution:            2710            10.336%
Too Short:              0               0.000%
```

vs

```
Assembled reads ...................: 25,490 / 26,220 (97.216%)
Discarded reads ...................: 0 / 26,220 (0.000%)
Not assembled reads ...............: 730 / 26,220 (2.784%)
```
I'm not familiar with BBMerge or it's parameters.
1) Is it OK to pre-merge the reads with PEAR and then pass them to itsxpress > qiime2 (DADA2) as single-end?
2) Does it indicate there's an issue with the samples? If not, maybe notify the user that reads were not paired properly (such report doesn't exist in qiime, as far as I know).

UPDATE:
After merging with PEAR, ~95% of the merged reads were successfully trimmed by itsxrpess.

Thanks,
Omer

**Comment by pilpel-lab** [comment]
[ITSxpress.log](https://github.com/USDA-ARS-GBRU/itsxpress/files/2561462/ITSxpress.log)

Attached is the log. I've reduced the minimal overlap to 8 bases in bbmerge and it didn't change the results, I also thought that I might be editing the wrong file so I ran pear with minimal overlap of 12, just like bbmerge, and it still managed to merge 97% of the reads.

It happens for almost(?) all the files of that lane, I've sent you a link via qiime forum messenger.
Also, I believe that the empty sequences issue I encounter is the result of bad merging and not necessarily contamination, because (probably) a lot of valid reads are thrown before reaching the trimming step.

**Comment by pilpel-lab** [comment]
I've sent you a link to all the fastq files over the qiime2 forum message board.
I used here files RDB64_S346_L001_R1_001.fastq.gz and RDB64_S346_L001_R2_001.fastq.gz.
I opened the issue here since I used the standalone version of ITSxpess...

Anyway, the lines that I edited in bbmerge.sh are
```
minoverlap=8        Minimum number of overlapping bases to allow merging. Default: 12
minoverlap0=6        Overlaps shorter than this will not be considered.
```
Which were 12 and 10, respectively (not sure about the latter).

I'll ask the developers at bbtools forums; just thought to let you know, since I lose a lot of my reads because of the pre-merging step and other users may be affected as well.

Thanks,
Omer

**Comment by arivers** [comment]
I ran this sample (RDB64_S346_L001_R1_001.fastq.gz/RDB64_S346_L001_R2_001.fastq.gz) and verified the difference in merging rates you reported. I just sent an email to my friend Brian Bushnell, the BBmerge developer, about the differences.

**Comment by arivers** [comment]
Hi Omer,

Brian looked at your data and here's what he said:

"I investigated this and found the answer:  As far as I can tell, these reads are super low quality, and the base scores do not accurately reflect that.  BBMerge's unmerged pairs contain on average around 40 mismatches, which is more than the program was designed to handle - it has a hard cap of 20 mismatches with no way to increase that.  So I added a flag allow increasing that number, "maxmismatches" (which will be in the next version).  After also changing some additional flags, I got this:

` bbmerge.sh in=interleaved.fq maxratio=0.5 ratiomargin=1.1 maxmismatches=100 efilter=f pfilter=f`

...which results in ~96% merge rate, by basically allowing up to half the bases to mismatch and virtually disabling all tests for ambiguity.  Which means that you would never want to do this if you care about false-positive merges.

Since this is some kind of amplicon sequencing with long overlaps, false positive merges are less of a problem than with randomly-sheared reads that might not overlap at all, since in this case usually the best overlap is correct.  I developed BBMerge primarily for fragment libraries, not amplicons, so it is geared toward ensuring the highest possible SNR and avoiding false-positives at all costs, rather than attempting to achieve the maximum possible merge rate.  PEAR, presumably, is aimed at amplicons designed to be overlapping.

Therefore, even though I am adding the capability to do this, I would make myself content with the default 45% merge rate of the highest-quality reads.  Adding in merged pairs that have 40+ mismatches is guaranteed to yield sequences with lots of incorrect base calls, which will make it hard to cluster, and lead to overestimates of the population diversity.  Really, I'd probably discard this data and re-run it with much more PhiX or something spiked in, or multiplexed with high-diversity libraries; looking at the base frequency histogram, it's clear that these reads have very poor color-balancing, with ~95% of the reads identical for the first 70bp.  Of course if they were already run with other sequences sufficient for color-balancing the flowcell overall, then I'm not really sure what the problem is.  It's hard to calculate the exact error rates or see which cycles they're in since there's no reference.

If you had PhiX in the lane, I'd suggest aligning some of it to calculate the error rates (with BBMap's mhist flag); it's possible that this was just an overall failed run."
